spring:
  config:
    activate:
      on-profile: local # 환경 이름 설정
  datasource:
    url: jdbc:mysql://localhost:3306/suzip
    username: root
    password: eldnj521!
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  security:
    user:
      name: suzip
      password: suzip
    oauth2:
      client:
        registration:
          kakao:
            client-id: 928ed937b1265fe6fe4b31ef64139a57
            client-secret: rBX6mmtMDsFuy4OxjH2vFhwK9BmCfu2u
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: # https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
              - profile_nickname
              - profile_image
              - account_email
#            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id # Kakao 응답 값 id, connected_at, properties, kakao_account 중 id 지정

# cors 설정
cors:
  allowed-origins: 'http://localhost:3000'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

# jwt secret key 설정
jwt.secret: '79yaos8grhfdhbakhgnaljdsjhfbekjwgvquy3i8vsajhdvjgsa'

# 토큰 관련 secret Key 및 RedirectUri 설정
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect